name: Back CI

on:
  push:
    paths:
      - 'Back/**'
      - 'Domain/**'
      - 'Application/**'
  pull_request:
    paths:
      - 'Back/**'
      - 'Domain/**'
      - 'Application/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Back/Api/Api.csproj

    - name: Build
      run: dotnet build Back/Api/Api.csproj --no-restore